import type { Candidate } from "./types";

// Seeded anonymous Madrid Padel players for the demo.
export const MADRID_PLAYERS: Candidate[] = [
  {
    id: "p1",
    handle: "TopspinTita",
    avatar: "🎾",
    gender: "woman",
    age: 29,
    ageMin: 27,
    ageMax: 36,
    interestedIn: ["man"],
    nationality: "Spain",
    zone: "Chamberí",
    level: "intermediate",
    priorities: ["funny", "intellectual", "adventurous", "fashionable", "looks"],
    bio: "Plays twice a week at Reserva. Reads on the metro.",
  },
  {
    id: "p2",
    handle: "GlassWallGuille",
    avatar: "🧊",
    gender: "man",
    age: 33,
    ageMin: 27,
    ageMax: 35,
    interestedIn: ["woman"],
    nationality: "Spain",
    zone: "Salamanca",
    level: "advanced",
    priorities: ["intellectual", "funny", "preserved", "adventurous", "looks"],
    bio: "Architect. Backhand needs work, lob is lethal.",
  },
  {
    id: "p3",
    handle: "BandejaBea",
    avatar: "🌙",
    gender: "woman",
    age: 31,
    ageMin: 29,
    ageMax: 38,
    interestedIn: ["man", "woman"],
    nationality: "Italy",
    zone: "Malasaña",
    level: "intermediate",
    priorities: ["adventurous", "funny", "fun", "intellectual", "social butterfly"],
    bio: "Roman in Madrid 4 years. Will play in the rain.",
  },
  {
    id: "p4",
    handle: "ViborasVíctor",
    avatar: "🐍",
    gender: "man",
    age: 35,
    ageMin: 28,
    ageMax: 36,
    interestedIn: ["woman"],
    nationality: "Argentina",
    zone: "Chamartín",
    level: "competitive",
    priorities: ["adventurous", "fun", "looks", "funny", "social butterfly"],
    bio: "Ex-tennis. Yes, the smash is dramatic.",
  },
  {
    id: "p5",
    handle: "QuietCourtClara",
    avatar: "🌿",
    gender: "woman",
    age: 27,
    ageMin: 26,
    ageMax: 34,
    interestedIn: ["man"],
    nationality: "Portugal",
    zone: "La Latina",
    level: "casual",
    priorities: ["quiet", "intellectual", "preserved", "funny", "adventurous"],
    bio: "PhD in something boring. Padel to disconnect.",
  },
  {
    id: "p6",
    handle: "ChiquitaCharo",
    avatar: "🍒",
    gender: "woman",
    age: 30,
    ageMin: 28,
    ageMax: 38,
    interestedIn: ["man"],
    nationality: "France",
    zone: "Chueca",
    level: "intermediate",
    priorities: ["fashionable", "fun", "social butterfly", "looks", "funny"],
    bio: "Parisienne, padel convert. Loves after-match vermut.",
  },
  {
    id: "p7",
    handle: "QuietRallyRafa",
    avatar: "🪐",
    gender: "man",
    age: 32,
    ageMin: 27,
    ageMax: 34,
    interestedIn: ["woman"],
    nationality: "Spain",
    zone: "Retiro",
    level: "intermediate",
    priorities: ["quiet", "intellectual", "preserved", "funny", "adventurous"],
    bio: "Editor. Will not yell '¡vamos!' but means it.",
  },
  {
    id: "p8",
    handle: "SocialSofi",
    avatar: "✨",
    gender: "woman",
    age: 28,
    ageMin: 26,
    ageMax: 34,
    interestedIn: ["man"],
    nationality: "Mexico",
    zone: "Centro",
    level: "casual",
    priorities: ["social butterfly", "fun", "funny", "fashionable", "adventurous"],
    bio: "New to Madrid. Looking for a regular pareja.",
  },
  {
    id: "p9",
    handle: "DropShotDani",
    avatar: "🔥",
    gender: "man",
    age: 30,
    ageMin: 25,
    ageMax: 33,
    interestedIn: ["woman"],
    nationality: "Spain",
    zone: "Moncloa",
    level: "advanced",
    priorities: ["fun", "adventurous", "funny", "looks", "social butterfly"],
    bio: "Devs by day, dejada by night.",
  },
  {
    id: "p10",
    handle: "BoastBlanca",
    avatar: "🌊",
    gender: "woman",
    age: 34,
    ageMin: 30,
    ageMax: 42,
    interestedIn: ["man"],
    nationality: "Spain",
    zone: "Salamanca",
    level: "advanced",
    priorities: ["preserved", "intellectual", "fashionable", "funny", "looks"],
    bio: "Lawyer. Court at 7am, no excuses.",
  },
  {
    id: "p11",
    handle: "LobLuca",
    avatar: "🍋",
    gender: "man",
    age: 29,
    ageMin: 26,
    ageMax: 33,
    interestedIn: ["woman", "non-binary"],
    nationality: "Italy",
    zone: "Malasaña",
    level: "casual",
    priorities: ["funny", "adventurous", "fun", "intellectual", "quiet"],
    bio: "Milanese. Cooks pasta after every match.",
  },
  {
    id: "p12",
    handle: "BajadaBruno",
    avatar: "⚡",
    gender: "man",
    age: 36,
    ageMin: 28,
    ageMax: 38,
    interestedIn: ["woman"],
    nationality: "Portugal",
    zone: "Tetuán",
    level: "intermediate",
    priorities: ["adventurous", "preserved", "funny", "quiet", "intellectual"],
    bio: "Quiet hitter. Saturday morning regular.",
  },
];

// Approximate distance score between two Madrid zones (lower is closer).
// Not real geo — a curated affinity matrix so the demo feels right.
const ZONE_CLUSTERS: Record<string, number> = {
  "Centro|Malasaña": 1, "Centro|Chueca": 1, "Centro|La Latina": 1, "Centro|Chamberí": 2,
  "Chamberí|Malasaña": 1, "Chamberí|Chamartín": 2, "Chamberí|Salamanca": 2,
  "Salamanca|Retiro": 1, "Salamanca|Chamartín": 2, "Salamanca|Chueca": 1,
  "Retiro|La Latina": 2, "Retiro|Centro": 2,
  "Malasaña|Chueca": 1, "Malasaña|La Latina": 2,
  "Moncloa|Chamberí": 2, "Moncloa|Tetuán": 2,
  "Tetuán|Chamartín": 1, "Tetuán|Chamberí": 2,
};

export function zoneAffinity(a: string, b: string): number {
  if (a === b) return 0;
  return ZONE_CLUSTERS[`${a}|${b}`] ?? ZONE_CLUSTERS[`${b}|${a}`] ?? 3;
}

// Cultural neighbor groups for nationality affinity.
const CULTURE_GROUPS: string[][] = [
  ["Spain", "Portugal"],
  ["Spain", "Italy", "France"],
  ["Italy", "France"],
  ["Spain", "Argentina", "Mexico"],
  ["Argentina", "Mexico"],
];

export function cultureAffinity(a: string, b: string): number {
  if (a === b) return 0;
  for (const g of CULTURE_GROUPS) if (g.includes(a) && g.includes(b)) return 1;
  return 2;
}
