/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PadelCercaDeMiRouteImport } from './routes/padel-cerca-de-mi'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FreePadelCourtsRouteImport } from './routes/free-padel-courts'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SCodeRouteImport } from './routes/s.$code'
import { Route as PreviewPlayerCardV2RouteImport } from './routes/preview.player-card-v2'
import { Route as PreviewPlayerCardRouteImport } from './routes/preview.player-card'
import { Route as PlayMadridRouteImport } from './routes/play.madrid'
import { Route as MEventIdRouteImport } from './routes/m.$eventId'
import { Route as GEventIdRouteImport } from './routes/g.$eventId'
import { Route as AppQuickStartRouteImport } from './routes/app.quick-start'
import { Route as AppQuestionsRouteImport } from './routes/app.questions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppJoinSetupRouteImport } from './routes/app.join-setup'
import { Route as AppHiddenRouteImport } from './routes/app.hidden'
import { Route as AppGridRouteImport } from './routes/app.grid'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known.apple-app-site-association'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppMatchesMatchIdRouteImport } from './routes/app.matches.$matchId'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AppEventsEventIdEditRouteImport } from './routes/app.events.$eventId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PadelCercaDeMiRoute = PadelCercaDeMiRouteImport.update({
  id: '/padel-cerca-de-mi',
  path: '/padel-cerca-de-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FreePadelCourtsRoute = FreePadelCourtsRouteImport.update({
  id: '/free-padel-courts',
  path: '/free-padel-courts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPlayerCardV2Route = PreviewPlayerCardV2RouteImport.update({
  id: '/preview/player-card-v2',
  path: '/preview/player-card-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPlayerCardRoute = PreviewPlayerCardRouteImport.update({
  id: '/preview/player-card',
  path: '/preview/player-card',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMadridRoute = PlayMadridRouteImport.update({
  id: '/madrid',
  path: '/madrid',
  getParentRoute: () => PlayRoute,
} as any)
const MEventIdRoute = MEventIdRouteImport.update({
  id: '/m/$eventId',
  path: '/m/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const GEventIdRoute = GEventIdRouteImport.update({
  id: '/g/$eventId',
  path: '/g/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuickStartRoute = AppQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinSetupRoute = AppJoinSetupRouteImport.update({
  id: '/join-setup',
  path: '/join-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppHiddenRoute = AppHiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => AppRoute,
} as any)
const AppGridRoute = AppGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesMatchIdRoute = AppMatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => AppMatchesRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEventsEventIdEditRoute = AppEventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/free-padel-courts': typeof FreePadelCourtsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/padel-cerca-de-mi': typeof PadelCercaDeMiRoute
  '/play': typeof PlayRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/app/admin': typeof AppAdminRoute
  '/app/connect': typeof AppConnectRoute
  '/app/grid': typeof AppGridRoute
  '/app/hidden': typeof AppHiddenRoute
  '/app/join-setup': typeof AppJoinSetupRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/quick-start': typeof AppQuickStartRoute
  '/g/$eventId': typeof GEventIdRoute
  '/m/$eventId': typeof MEventIdRoute
  '/play/madrid': typeof PlayMadridRoute
  '/preview/player-card': typeof PreviewPlayerCardRoute
  '/preview/player-card-v2': typeof PreviewPlayerCardV2Route
  '/s/$code': typeof SCodeRoute
  '/app/': typeof AppIndexRoute
  '/play/': typeof PlayIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/free-padel-courts': typeof FreePadelCourtsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/padel-cerca-de-mi': typeof PadelCercaDeMiRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/app/admin': typeof AppAdminRoute
  '/app/connect': typeof AppConnectRoute
  '/app/grid': typeof AppGridRoute
  '/app/hidden': typeof AppHiddenRoute
  '/app/join-setup': typeof AppJoinSetupRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/quick-start': typeof AppQuickStartRoute
  '/g/$eventId': typeof GEventIdRoute
  '/m/$eventId': typeof MEventIdRoute
  '/play/madrid': typeof PlayMadridRoute
  '/preview/player-card': typeof PreviewPlayerCardRoute
  '/preview/player-card-v2': typeof PreviewPlayerCardV2Route
  '/s/$code': typeof SCodeRoute
  '/app': typeof AppIndexRoute
  '/play': typeof PlayIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/free-padel-courts': typeof FreePadelCourtsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/padel-cerca-de-mi': typeof PadelCercaDeMiRoute
  '/play': typeof PlayRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/app/admin': typeof AppAdminRoute
  '/app/connect': typeof AppConnectRoute
  '/app/grid': typeof AppGridRoute
  '/app/hidden': typeof AppHiddenRoute
  '/app/join-setup': typeof AppJoinSetupRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/quick-start': typeof AppQuickStartRoute
  '/g/$eventId': typeof GEventIdRoute
  '/m/$eventId': typeof MEventIdRoute
  '/play/madrid': typeof PlayMadridRoute
  '/preview/player-card': typeof PreviewPlayerCardRoute
  '/preview/player-card-v2': typeof PreviewPlayerCardV2Route
  '/s/$code': typeof SCodeRoute
  '/app/': typeof AppIndexRoute
  '/play/': typeof PlayIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/demo'
    | '/free-padel-courts'
    | '/how-it-works'
    | '/padel-cerca-de-mi'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/app/admin'
    | '/app/connect'
    | '/app/grid'
    | '/app/hidden'
    | '/app/join-setup'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/app/quick-start'
    | '/g/$eventId'
    | '/m/$eventId'
    | '/play/madrid'
    | '/preview/player-card'
    | '/preview/player-card-v2'
    | '/s/$code'
    | '/app/'
    | '/play/'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/matches/$matchId'
    | '/app/events/'
    | '/app/events/$eventId/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/free-padel-courts'
    | '/how-it-works'
    | '/padel-cerca-de-mi'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/app/admin'
    | '/app/connect'
    | '/app/grid'
    | '/app/hidden'
    | '/app/join-setup'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/app/quick-start'
    | '/g/$eventId'
    | '/m/$eventId'
    | '/play/madrid'
    | '/preview/player-card'
    | '/preview/player-card-v2'
    | '/s/$code'
    | '/app'
    | '/play'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/matches/$matchId'
    | '/app/events'
    | '/app/events/$eventId/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/demo'
    | '/free-padel-courts'
    | '/how-it-works'
    | '/padel-cerca-de-mi'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/.well-known/apple-app-site-association'
    | '/app/admin'
    | '/app/connect'
    | '/app/grid'
    | '/app/hidden'
    | '/app/join-setup'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/app/quick-start'
    | '/g/$eventId'
    | '/m/$eventId'
    | '/play/madrid'
    | '/preview/player-card'
    | '/preview/player-card-v2'
    | '/s/$code'
    | '/app/'
    | '/play/'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/matches/$matchId'
    | '/app/events/'
    | '/app/events/$eventId/edit'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  FreePadelCourtsRoute: typeof FreePadelCourtsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PadelCercaDeMiRoute: typeof PadelCercaDeMiRoute
  PlayRoute: typeof PlayRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  GEventIdRoute: typeof GEventIdRoute
  MEventIdRoute: typeof MEventIdRoute
  PreviewPlayerCardRoute: typeof PreviewPlayerCardRoute
  PreviewPlayerCardV2Route: typeof PreviewPlayerCardV2Route
  SCodeRoute: typeof SCodeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/padel-cerca-de-mi': {
      id: '/padel-cerca-de-mi'
      path: '/padel-cerca-de-mi'
      fullPath: '/padel-cerca-de-mi'
      preLoaderRoute: typeof PadelCercaDeMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-padel-courts': {
      id: '/free-padel-courts'
      path: '/free-padel-courts'
      fullPath: '/free-padel-courts'
      preLoaderRoute: typeof FreePadelCourtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/player-card-v2': {
      id: '/preview/player-card-v2'
      path: '/preview/player-card-v2'
      fullPath: '/preview/player-card-v2'
      preLoaderRoute: typeof PreviewPlayerCardV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/player-card': {
      id: '/preview/player-card'
      path: '/preview/player-card'
      fullPath: '/preview/player-card'
      preLoaderRoute: typeof PreviewPlayerCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/madrid': {
      id: '/play/madrid'
      path: '/madrid'
      fullPath: '/play/madrid'
      preLoaderRoute: typeof PlayMadridRouteImport
      parentRoute: typeof PlayRoute
    }
    '/m/$eventId': {
      id: '/m/$eventId'
      path: '/m/$eventId'
      fullPath: '/m/$eventId'
      preLoaderRoute: typeof MEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$eventId': {
      id: '/g/$eventId'
      path: '/g/$eventId'
      fullPath: '/g/$eventId'
      preLoaderRoute: typeof GEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/quick-start': {
      id: '/app/quick-start'
      path: '/quick-start'
      fullPath: '/app/quick-start'
      preLoaderRoute: typeof AppQuickStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions': {
      id: '/app/questions'
      path: '/questions'
      fullPath: '/app/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/join-setup': {
      id: '/app/join-setup'
      path: '/join-setup'
      fullPath: '/app/join-setup'
      preLoaderRoute: typeof AppJoinSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hidden': {
      id: '/app/hidden'
      path: '/hidden'
      fullPath: '/app/hidden'
      preLoaderRoute: typeof AppHiddenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grid': {
      id: '/app/grid'
      path: '/grid'
      fullPath: '/app/grid'
      preLoaderRoute: typeof AppGridRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches/$matchId': {
      id: '/app/matches/$matchId'
      path: '/$matchId'
      fullPath: '/app/matches/$matchId'
      preLoaderRoute: typeof AppMatchesMatchIdRouteImport
      parentRoute: typeof AppMatchesRoute
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/events/$eventId/edit': {
      id: '/app/events/$eventId/edit'
      path: '/edit'
      fullPath: '/app/events/$eventId/edit'
      preLoaderRoute: typeof AppEventsEventIdEditRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AppMatchesRouteChildren {
  AppMatchesMatchIdRoute: typeof AppMatchesMatchIdRoute
}

const AppMatchesRouteChildren: AppMatchesRouteChildren = {
  AppMatchesMatchIdRoute: AppMatchesMatchIdRoute,
}

const AppMatchesRouteWithChildren = AppMatchesRoute._addFileChildren(
  AppMatchesRouteChildren,
)

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdEditRoute: typeof AppEventsEventIdEditRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdEditRoute: AppEventsEventIdEditRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppConnectRoute: typeof AppConnectRoute
  AppGridRoute: typeof AppGridRoute
  AppHiddenRoute: typeof AppHiddenRoute
  AppJoinSetupRoute: typeof AppJoinSetupRoute
  AppMatchesRoute: typeof AppMatchesRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppQuickStartRoute: typeof AppQuickStartRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppConnectRoute: AppConnectRoute,
  AppGridRoute: AppGridRoute,
  AppHiddenRoute: AppHiddenRoute,
  AppJoinSetupRoute: AppJoinSetupRoute,
  AppMatchesRoute: AppMatchesRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppQuickStartRoute: AppQuickStartRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlayRouteChildren {
  PlayMadridRoute: typeof PlayMadridRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayMadridRoute: PlayMadridRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  FreePadelCourtsRoute: FreePadelCourtsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PadelCercaDeMiRoute: PadelCercaDeMiRoute,
  PlayRoute: PlayRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  GEventIdRoute: GEventIdRoute,
  MEventIdRoute: MEventIdRoute,
  PreviewPlayerCardRoute: PreviewPlayerCardRoute,
  PreviewPlayerCardV2Route: PreviewPlayerCardV2Route,
  SCodeRoute: SCodeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
