/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayRouteImport } from './routes/play'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as MEventIdRouteImport } from './routes/m.$eventId'
import { Route as GEventIdRouteImport } from './routes/g.$eventId'
import { Route as AppQuestionsRouteImport } from './routes/app.questions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppJoinSetupRouteImport } from './routes/app.join-setup'
import { Route as AppHiddenRouteImport } from './routes/app.hidden'
import { Route as AppGridRouteImport } from './routes/app.grid'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AppMatchesMatchIdRouteImport } from './routes/app.matches.$matchId'
import { Route as AppEventsNewRouteImport } from './routes/app.events.new'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as AppEventsEventIdEditRouteImport } from './routes/app.events.$eventId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const MEventIdRoute = MEventIdRouteImport.update({
  id: '/m/$eventId',
  path: '/m/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const GEventIdRoute = GEventIdRouteImport.update({
  id: '/g/$eventId',
  path: '/g/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinSetupRoute = AppJoinSetupRouteImport.update({
  id: '/join-setup',
  path: '/join-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppHiddenRoute = AppHiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => AppRoute,
} as any)
const AppGridRoute = AppGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesMatchIdRoute = AppMatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => AppMatchesRoute,
} as any)
const AppEventsNewRoute = AppEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdEditRoute = AppEventsEventIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppEventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/connect': typeof AppConnectRoute
  '/app/grid': typeof AppGridRoute
  '/app/hidden': typeof AppHiddenRoute
  '/app/join-setup': typeof AppJoinSetupRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/g/$eventId': typeof GEventIdRoute
  '/m/$eventId': typeof MEventIdRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/connect': typeof AppConnectRoute
  '/app/grid': typeof AppGridRoute
  '/app/hidden': typeof AppHiddenRoute
  '/app/join-setup': typeof AppJoinSetupRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/g/$eventId': typeof GEventIdRoute
  '/m/$eventId': typeof MEventIdRoute
  '/app': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/how-it-works': typeof HowItWorksRoute
  '/play': typeof PlayRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/connect': typeof AppConnectRoute
  '/app/grid': typeof AppGridRoute
  '/app/hidden': typeof AppHiddenRoute
  '/app/join-setup': typeof AppJoinSetupRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/g/$eventId': typeof GEventIdRoute
  '/m/$eventId': typeof MEventIdRoute
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/events/new': typeof AppEventsNewRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/events/$eventId/edit': typeof AppEventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/how-it-works'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/app/admin'
    | '/app/connect'
    | '/app/grid'
    | '/app/hidden'
    | '/app/join-setup'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/g/$eventId'
    | '/m/$eventId'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/matches/$matchId'
    | '/app/events/'
    | '/app/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/how-it-works'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/app/admin'
    | '/app/connect'
    | '/app/grid'
    | '/app/hidden'
    | '/app/join-setup'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/g/$eventId'
    | '/m/$eventId'
    | '/app'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/matches/$matchId'
    | '/app/events'
    | '/app/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/how-it-works'
    | '/play'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/app/admin'
    | '/app/connect'
    | '/app/grid'
    | '/app/hidden'
    | '/app/join-setup'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/g/$eventId'
    | '/m/$eventId'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/events/new'
    | '/app/matches/$matchId'
    | '/app/events/'
    | '/app/events/$eventId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlayRoute: typeof PlayRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  GEventIdRoute: typeof GEventIdRoute
  MEventIdRoute: typeof MEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/m/$eventId': {
      id: '/m/$eventId'
      path: '/m/$eventId'
      fullPath: '/m/$eventId'
      preLoaderRoute: typeof MEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$eventId': {
      id: '/g/$eventId'
      path: '/g/$eventId'
      fullPath: '/g/$eventId'
      preLoaderRoute: typeof GEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/questions': {
      id: '/app/questions'
      path: '/questions'
      fullPath: '/app/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/join-setup': {
      id: '/app/join-setup'
      path: '/join-setup'
      fullPath: '/app/join-setup'
      preLoaderRoute: typeof AppJoinSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hidden': {
      id: '/app/hidden'
      path: '/hidden'
      fullPath: '/app/hidden'
      preLoaderRoute: typeof AppHiddenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grid': {
      id: '/app/grid'
      path: '/grid'
      fullPath: '/app/grid'
      preLoaderRoute: typeof AppGridRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches/$matchId': {
      id: '/app/matches/$matchId'
      path: '/$matchId'
      fullPath: '/app/matches/$matchId'
      preLoaderRoute: typeof AppMatchesMatchIdRouteImport
      parentRoute: typeof AppMatchesRoute
    }
    '/app/events/new': {
      id: '/app/events/new'
      path: '/events/new'
      fullPath: '/app/events/new'
      preLoaderRoute: typeof AppEventsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events/$eventId/edit': {
      id: '/app/events/$eventId/edit'
      path: '/edit'
      fullPath: '/app/events/$eventId/edit'
      preLoaderRoute: typeof AppEventsEventIdEditRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AppMatchesRouteChildren {
  AppMatchesMatchIdRoute: typeof AppMatchesMatchIdRoute
}

const AppMatchesRouteChildren: AppMatchesRouteChildren = {
  AppMatchesMatchIdRoute: AppMatchesMatchIdRoute,
}

const AppMatchesRouteWithChildren = AppMatchesRoute._addFileChildren(
  AppMatchesRouteChildren,
)

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdEditRoute: typeof AppEventsEventIdEditRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdEditRoute: AppEventsEventIdEditRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppConnectRoute: typeof AppConnectRoute
  AppGridRoute: typeof AppGridRoute
  AppHiddenRoute: typeof AppHiddenRoute
  AppJoinSetupRoute: typeof AppJoinSetupRoute
  AppMatchesRoute: typeof AppMatchesRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
  AppEventsNewRoute: typeof AppEventsNewRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppConnectRoute: AppConnectRoute,
  AppGridRoute: AppGridRoute,
  AppHiddenRoute: AppHiddenRoute,
  AppJoinSetupRoute: AppJoinSetupRoute,
  AppMatchesRoute: AppMatchesRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
  AppEventsNewRoute: AppEventsNewRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlayRoute: PlayRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  GEventIdRoute: GEventIdRoute,
  MEventIdRoute: MEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
