/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppQuestionsRouteImport } from './routes/app.questions'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppMatchesMatchIdRouteImport } from './routes/app.matches.$matchId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionsRoute = AppQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesMatchIdRoute = AppMatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => AppMatchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/': typeof AppIndexRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app': typeof AppIndexRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/matches': typeof AppMatchesRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/questions': typeof AppQuestionsRoute
  '/app/': typeof AppIndexRoute
  '/app/matches/$matchId': typeof AppMatchesMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/admin'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/app/'
    | '/app/matches/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/admin'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/app'
    | '/app/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/app/admin'
    | '/app/matches'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/questions'
    | '/app/'
    | '/app/matches/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/questions': {
      id: '/app/questions'
      path: '/questions'
      fullPath: '/app/questions'
      preLoaderRoute: typeof AppQuestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches/$matchId': {
      id: '/app/matches/$matchId'
      path: '/$matchId'
      fullPath: '/app/matches/$matchId'
      preLoaderRoute: typeof AppMatchesMatchIdRouteImport
      parentRoute: typeof AppMatchesRoute
    }
  }
}

interface AppMatchesRouteChildren {
  AppMatchesMatchIdRoute: typeof AppMatchesMatchIdRoute
}

const AppMatchesRouteChildren: AppMatchesRouteChildren = {
  AppMatchesMatchIdRoute: AppMatchesMatchIdRoute,
}

const AppMatchesRouteWithChildren = AppMatchesRoute._addFileChildren(
  AppMatchesRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppMatchesRoute: typeof AppMatchesRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuestionsRoute: typeof AppQuestionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppMatchesRoute: AppMatchesRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuestionsRoute: AppQuestionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
